name: Frontend Deploy

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deploy.yml"
  workflow_run:
    workflows: ["Infra Deploy"]
    types:
      - completed

jobs:
  get-infra-outputs:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
    permissions:
      id-token: write
      contents: read
    outputs:
      items-api-url: ${{ steps.outputs.outputs.items-api-url }}
      user-pool-id: ${{ steps.outputs.outputs.user-pool-id }}
      client-id: ${{ steps.outputs.outputs.client-id }}
      cognito-domain: ${{ steps.outputs.outputs.cognito-domain }}
      site-bucket: ${{ steps.outputs.outputs.site-bucket }}
      distribution-id: ${{ steps.outputs.outputs.distribution-id }}
    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsLacatuRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get stack outputs
        id: outputs
        run: |
          ITEMS_API_URL=$(aws cloudformation describe-stacks --stack-name LacatuStack --query 'Stacks[0].Outputs[?OutputKey==`ItemsApiBaseUrl`].OutputValue' --output text)
          USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name LacatuStack --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' --output text)
          CLIENT_ID=$(aws cloudformation describe-stacks --stack-name LacatuStack --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' --output text)
          COGNITO_DOMAIN=$(aws cloudformation describe-stacks --stack-name LacatuStack --query 'Stacks[0].Outputs[?OutputKey==`CognitoDomain`].OutputValue' --output text)
          SITE_BUCKET=$(aws cloudformation describe-stacks --stack-name LacatuStack --query 'Stacks[0].Outputs[?OutputKey==`SiteBucketName`].OutputValue' --output text)
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name LacatuStack --query 'Stacks[0].Outputs[?OutputKey==`DistributionId`].OutputValue' --output text)
          
          echo "items-api-url=$ITEMS_API_URL" >> $GITHUB_OUTPUT
          echo "user-pool-id=$USER_POOL_ID" >> $GITHUB_OUTPUT
          echo "client-id=$CLIENT_ID" >> $GITHUB_OUTPUT
          echo "cognito-domain=$COGNITO_DOMAIN" >> $GITHUB_OUTPUT
          echo "site-bucket=$SITE_BUCKET" >> $GITHUB_OUTPUT
          echo "distribution-id=$DISTRIBUTION_ID" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: [get-infra-outputs]
    if: always() && (github.event_name == 'push' || needs.get-infra-outputs.result == 'success')
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsLacatuRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Check formatting
        run: |
          cd frontend
          npm run format:check

      - name: Lint code
        run: |
          cd frontend
          npm run lint

      - name: Get stack outputs (for push events)
        if: github.event_name == 'push'
        id: stack-outputs
        run: |
          ITEMS_API_URL=$(aws cloudformation describe-stacks --stack-name LacatuStack --query 'Stacks[0].Outputs[?OutputKey==`ItemsApiBaseUrl`].OutputValue' --output text)
          USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name LacatuStack --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' --output text)
          CLIENT_ID=$(aws cloudformation describe-stacks --stack-name LacatuStack --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' --output text)
          COGNITO_DOMAIN=$(aws cloudformation describe-stacks --stack-name LacatuStack --query 'Stacks[0].Outputs[?OutputKey==`CognitoDomain`].OutputValue' --output text)
          SITE_BUCKET=$(aws cloudformation describe-stacks --stack-name LacatuStack --query 'Stacks[0].Outputs[?OutputKey==`SiteBucketName`].OutputValue' --output text)
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name LacatuStack --query 'Stacks[0].Outputs[?OutputKey==`DistributionId`].OutputValue' --output text)
          
          echo "items-api-url=$ITEMS_API_URL" >> $GITHUB_OUTPUT
          echo "user-pool-id=$USER_POOL_ID" >> $GITHUB_OUTPUT
          echo "client-id=$CLIENT_ID" >> $GITHUB_OUTPUT
          echo "cognito-domain=$COGNITO_DOMAIN" >> $GITHUB_OUTPUT
          echo "site-bucket=$SITE_BUCKET" >> $GITHUB_OUTPUT
          echo "distribution-id=$DISTRIBUTION_ID" >> $GITHUB_OUTPUT

      - name: Build frontend
        run: |
          cd frontend
          ITEMS_API_URL=${{ github.event_name == 'push' && steps.stack-outputs.outputs.items-api-url || needs.get-infra-outputs.outputs.items-api-url }}
          USER_POOL=${{ github.event_name == 'push' && steps.stack-outputs.outputs.user-pool-id || needs.get-infra-outputs.outputs.user-pool-id }}
          CLIENT_ID=${{ github.event_name == 'push' && steps.stack-outputs.outputs.client-id || needs.get-infra-outputs.outputs.client-id }}
          COGNITO_DOMAIN=${{ github.event_name == 'push' && steps.stack-outputs.outputs.cognito-domain || needs.get-infra-outputs.outputs.cognito-domain }}
          
          echo "VITE_ITEMS_API_URL=$ITEMS_API_URL" >> .env
          echo "VITE_API_BASE_URL=$ITEMS_API_URL" >> .env
          echo "VITE_COGNITO_USER_POOL_ID=$USER_POOL" >> .env
          echo "VITE_COGNITO_CLIENT_ID=$CLIENT_ID" >> .env
          echo "VITE_COGNITO_DOMAIN=$COGNITO_DOMAIN" >> .env
          npm run build

      - name: Upload to S3
        run: |
          BUCKET=${{ github.event_name == 'push' && steps.stack-outputs.outputs.site-bucket || needs.get-infra-outputs.outputs.site-bucket }}
          aws s3 sync frontend/dist/ s3://$BUCKET --delete

      - name: Invalidate CloudFront
        run: |
          DIST_ID=${{ github.event_name == 'push' && steps.stack-outputs.outputs.distribution-id || needs.get-infra-outputs.outputs.distribution-id }}
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
