name: Infra Deploy

on:
  push:
    branches: [main]
    paths:
      - "infra/**"
      - "backend/**"
      - ".github/workflows/infra-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsLakituRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build backend (shadowJar)
        run: |
          cd backend
          ./gradlew clean shadowJar || ./gradlew.bat clean shadowJar

      - name: Install CDK deps
        run: |
          cd infra
          npm ci

      - name: CDK Bootstrap (no-op if already bootstrapped)
        run: |
          cd infra
          npx cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID || '' }}/${{ secrets.AWS_REGION }}

      - name: CDK deploy (app only)
        working-directory: infra
        run: |
          npm run build
          npx cdk deploy LakituStack --require-approval never
