name: Infra Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "infra/**"
      - "backend/**"
      - ".github/workflows/infra-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build backend (shadowJar)
        run: |
          cd backend
          ./gradlew clean shadowJar || ./gradlew.bat clean shadowJar

      - name: Install CDK deps
        run: |
          cd infra
          npm ci

      - name: CDK Bootstrap (no-op if already bootstrapped)
        run: |
          cd infra
          npx cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID || '' }}/${{ secrets.AWS_REGION }}

      - name: CDK Deploy
        run: |
          cd infra
          npm run build
          npx cdk deploy --all --require-approval never